export { default as ArticleDetails } from './ui/details/Details'
export { default as ArticleList } from './ui/list/List'
export { default } from './ui/card/ArticleCard'
export { type ArticleDetailsType } from './model/articleDetails'
export { type ArticleType } from './model/article'
